# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-13 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('try_test', '0002_auto_20171213_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrlManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='shorturl',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
